# this builds with linux/g++ however, travis-ci's 
# linux compilers are hopelessly out of date.
os: osx
osx_image: xcode7.3
language: cpp
compiler: 
  - clang
#  - gcc
before_script: 
  - mkdir build
  - cd build
  - cmake ..
script: make
before_install:
  - brew update
  - brew install ragel
  - brew install "https://github.com/ksherlock/lemon--/raw/master/lemon++.rb"

